/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentCard: typeof import('./components/AgentCard.vue')['default']
    AppShell: typeof import('./components/AppShell.vue')['default']
    ChatQuickPanel: typeof import('./components/chat/ChatQuickPanel.vue')['default']
    ConstructionPage: typeof import('./components/ConstructionPage.vue')['default']
    CustomizedResource: typeof import('./components/resource/CustomizedResource.vue')['default']
    DifficultyBadge: typeof import('./components/DifficultyBadge.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorState: typeof import('./components/ErrorState.vue')['default']
    EventTimeline: typeof import('./components/agent/EventTimeline.vue')['default']
    FinalCard: typeof import('./components/agent/FinalCard.vue')['default']
    MetricCard: typeof import('./components/MetricCard.vue')['default']
    NetBanner: typeof import('./components/NetBanner.vue')['default']
    ParticleFlow: typeof import('./components/agent/ParticleFlow.vue')['default']
    PracticeGuide: typeof import('./components/resource/PracticeGuide.vue')['default']
    RouteProgress: typeof import('./components/RouteProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutsDialog: typeof import('./components/ShortcutsDialog.vue')['default']
    SideNav: typeof import('./components/SideNav.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
    TieredQuiz: typeof import('./components/resource/TieredQuiz.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
    TypewriterBubble: typeof import('./components/agent/TypewriterBubble.vue')['default']
  }
}
